#!/bin/bash

if [ $# -eq 2 ]; then
	station_id=$1;
	isPremium=$2;
else
	echo "usage : $0 station_id isPremium<0,1>"
	exit 1
fi

. common/base.sh
HOME_PATH=`echo \`pwd\` | sed -e 's|/sh||g'`

API_URL="`$COMMON_PATH/getParam common api_url`"

AUTH_KEY="$TEMP_PATH/`$COMMON_PATH/getParam premium auth_key`"
COOKIE_FILE="$TEMP_PATH/`$COMMON_PATH/getParam premium cookie_file`"
AREA_FILE="$TEMP_PATH/`$COMMON_PATH/getParam common area_file`"

TEXT=`cat $AUTH_KEY`; IFS=','
set -- $TEXT
authtoken=$1
partialkey=$2
paid_member=$3
if [ "$paid_member" == "" ]; then
	paid_member=0
fi

if [ $paid_member -eq 3 -a $isPremium -eq 0 ]; then
##################################
# Premium 
##################################
	area_id="premium";
	area_name=$area_id;

	wget -q -T $HTTP_TIMEOUT -U "$USER_AGENT" -O $station_id-program.xml $API_URL/program/station/today?station_id=$station_id
	if [ $? -eq 0 -a -s $station_id-program.xml ]; then
		status="Station is Found."
		ret=0
	else
		status="Station is not Found."
		ret=1
	fi
	rm -rf $station_id-program.xml
	message="$area_name|$status($area_id)";

else
##################################
# not Premium 
##################################
	area_id=`perl -ne 'print $1 if(/^([^,]+),([^,]+),([^,]+)/i)' $AREA_FILE`
	rm -rf $AREA_FILE

	message=`common/checkIPArea $area_id $station_id`
	ret=$?
fi

echo -n $message
exit $ret

