#!/bin/bash


HOME_PATH=`echo \`pwd\` | sed -e 's/\/sh//g'`
PROG_PATH=$HOME_PATH
COMMON_PATH=$HOME_PATH/common
RADIKO_COMMON=$PROG_PATH/common

TEMP_PATH=$HOME_PATH/share/temp

. $RADIKO_COMMON/base.sh

##############################################
url=`$COMMON_PATH/getParam premium auth_url`

COOKIE_FILE="$TEMP_PATH/`$COMMON_PATH/getParam premium cookie_file`"
##############################################

####################################
# Logout Function
####################################
wget -q -T $HTTP_TIMEOUT -U "$USER_AGENT" \
	--no-check-certificate \
	--load-cookies $COOKIE_FILE \
	--save-headers \
	-O /dev/null \
	$url/webapi/member/logout

if [ -f $COOKIE_FILE ]; then
	rm -f $COOKIE_FILE
fi
echo -n "logouted."


