#!/bin/bash


. common/base.sh
HOME_PATH=`echo \`pwd\` | sed -e 's|/sh||g'`

##############################################
url=`$COMMON_PATH/getParam premium auth_url`

COOKIE_FILE="$TEMP_PATH/`$COMMON_PATH/getParam premium cookie_file`"
##############################################

####################################
# Logout Function
####################################
wget -q -T $HTTP_TIMEOUT -U "$USER_AGENT" \
	--no-check-certificate \
	--load-cookies $COOKIE_FILE \
	--save-headers \
	-O /dev/null \
	$url/webapi/member/logout

if [ -f $COOKIE_FILE ]; then
	rm -f $COOKIE_FILE
fi
echo -n "logouted."


