#!/usr/bin/perl --

use strict;
use Config::Simple;
use File::Spec;
use LWP::UserAgent;

my ($ua, $cfg);

my $home_path = File::Spec->rel2abs();
my $prog_path = "$home_path";
my $temp_path = "share/temp";
$home_path =~ s/__FILE__//g;

$cfg = new Config::Simple("$home_path/radiko.ini")->vars();

my $cookie_file = "$home_path/$temp_path/" . $cfg->{'premium.cookie_file'};
my $auth_key = "$home_path/$temp_path/" . $cfg->{'premium.auth_key'};

my $url = $cfg->{'premium.auth_url'};
my $timeout = $cfg->{'common.http_timeout'};
my $user_agent = `$prog_path/common/makeUserAgent radiko.jp $cfg->{'common.player_ver'}`;

$ua = LWP::UserAgent->new;
$ua->timeout($timeout);
$ua->agent($user_agent);
$ua->cookie_jar({file => $cookie_file, autosave => 1});

$ua->get($url . '/webapi/member/logout');
print "logouted.";

exit 0;

