#!/usr/bin/perl --

#
#
#

use strict;
use Config::Simple;
use File::Spec;
use LWP::UserAgent;
use XML::Simple;

if (@ARGV != 2){
	print "usage: " . __FILE__ . " area_id station_id\n";
	exit 1;
}

my ($ua, $req, $res, $cfg);

my $area_id = $ARGV[0];
my $station_id = $ARGV[1];

my $home_path = File::Spec->rel2abs();
$home_path =~ s/__FILE__//g;
my $prog_path = "$home_path";

$cfg = new Config::Simple("$prog_path/radiko.ini")->vars();
my $timeout = $cfg->{'common.http_timeout'};
my $user_agent = `$prog_path/common/makeUserAgent radiko.jp $cfg->{'common.player_ver'}`;

$ua = LWP::UserAgent->new;
$ua->timeout($timeout);
$ua->agent($user_agent);

$req = HTTP::Request->new(GET => 'http://radiko.jp/v2/station/list/' . $area_id . '.xml');
$res = $ua->request($req);

if (!$res->is_success) {
	print "Station is not Found. But, please look at the state because it might be all right in the area determined.|Unknown\n";
	exit 0;
}

my $data = XML::Simple->new(keyattr => [])->XMLin($res->content);

my ($channel, $station, $status, $ret);
foreach $station (@{$data->{'station'}}){
	$channel = $station->{'id'};
	if($channel eq $station_id){
		last;
	}
}
if($channel eq $station_id){
	$status = "Station is Found.";
	$ret = 0;
} else {
	$status = "Station is not Found.";
	$ret = 1;
}

print "$data->{'area_name'}|$status($area_id)";
exit $ret;

