#!/usr/bin/perl --

use strict;
use Config::Simple;
use File::Spec;
use LWP::UserAgent;
use XML::Simple;
use Encode;
use Unicode::Japanese;

if (@ARGV != 1){
	print "usage: " . __FILE__ . " station_id\n";
	exit 1;
}

my ($ua, $res, $cfg, $data);

my $home_path = File::Spec->rel2abs();
$home_path =~ s/__FILE__//g;

$cfg = new Config::Simple($home_path . '/radiko.ini')->vars();
my $api_url = $cfg->{'common.api_url'};
my $timeout = $cfg->{'common.http_timeout'};
my $user_agent = $cfg->{'common.mozilla_agent'} .' (' . $cfg->{'common.user_agent'} . ') radiko.jp/' . $cfg->{'common.player_ver'};

my $station_id = $ARGV[0];

$ua = LWP::UserAgent->new;
$ua->timeout($timeout);
$ua->agent($user_agent);

$res = $ua->get($api_url . '/program/station/today?station_id=' . $station_id);
if (!$res->is_success) {
	print "Station is not Found.\n";
	exit 1;
}

$data = XML::Simple->new(keyattr => [])->XMLin($res->content);
my $station_name = encode('utf-8', $data->{"stations"}->{"station"}->{"name"} . "\n");
$station_name = Unicode::Japanese->new($station_name)->z2h->get;
$station_name = Unicode::Japanese->new($station_name)->h2zKana->get;
print "$station_name";
exit 0;


